# action.yml
name: 'Issue dependency graph'
description: 'Make and sync a dep graph'
inputs:
  repo:  # id of input
    description: 'Repository to run on'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.repo }}
    - ${{ secrets.GITHUB_TOKEN }}
